name: flip_panel
description: A package for flip panel with built-in animation
version: 0.0.8
author: hunghd <hunghd.yb@gmail.com>
homepage: https://github.com/hnvn/flutter_flip_panel

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

